### ISSUE TITLE
[aptcc] tryToInstall BrokenFix unused

### ISSUE THREAD

**Issue by apachelogger** [PackageKit/PackageKit#152]
`AptCacheFile::tryToInstall`  completely ignores the BrokenFix parameter

```
bool AptCacheFile::tryToInstall(pkgProblemResolver &Fix,
                                const pkgCache::VerIterator &ver,
                                bool BrokenFix)
```

↓
Never gets used.

**Comment by ximion** [comment]
Maybe someone added this in order to implement `RepairSystem()`, but this seems to be done by other means now. => Remove it.
