### ISSUE TITLE
[aptcc] DPkg::Pre-Invoke is ignored

### ISSUE THREAD

**Issue by aleixpol** [PackageKit/PackageKit#281]
As described in https://bugs.kde.org/show_bug.cgi?id=395921

If I set up the environment that rejects all `DPkg::Pre-Invoke`, I get the following behaviour where apt is properly rejecting but pkcon just proceeds.

```
$ sudo apt install marble
The following NEW packages will be installed:
  marble
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/199 kB of archives.
After this operation, 1093 kB of additional disk space will be used.
E: Problem executing scripts DPkg::Pre-Invoke 'false'
E: Sub-process returned an error code
```
```
$ pkcon install marble
Resolving                     [=========================]        
Querying                      [=========================]        
Testing changes               [=========================]        
Finished                      [=========================]        
Installing                    [=========================]        
Waiting for authentication    [=========================]         map widget
Loading cache                 [=========================]        
Running                       [=========================]        
Installing packages           [=========================]        
Finished
```

**Comment by julian-klode** [comment]
Does it really proceed or just do nothing at all?

**Comment by wrix** [comment]
I can confirm the issue, basically, pkcon ignores `DPkg::Pre-Invoke` and proceeds to perform an install, remove, system upgrade, etc. This is a critical issue for users who have installed `apt-btrfs-snapshot` or similar packages and do not find snapshots in case of a situation that requires rollback to a previous state, especially in case of a bad upgrade.

**Comment by ximion** [comment]
@julian-klode How can APT/aptcc proceed here, if dpkg clearly fails? Are we not checking an error somewhere in aptcc (I had a look and found no obvious place).

**Comment by julian-klode** [comment]
I can't confirm this, it works fine for me. I have snapper installed and it created a snapshot in both pre-invoke and post-invoke scripts as it should.

**Comment by julian-klode** [comment]
Errors are checked just fine. The scripts are run inside of apt's pkgDPkgPM::Go()
