### ISSUE TITLE
A misbehaving PPA makes it impossible to refresh the PackageKit cache, makes PK crash and makes it impossible to perform any updates.

### ISSUE THREAD

**Issue by ripefig** [PackageKit/PackageKit#302]
I've always had problems with PPA and COPR repos bringing down all of packagekit. If a PPA is unreachable or drops a release that corresponds to your system, packagekit will crash while refreshing its cache and will no longer be able to perform _any_ updates, until you disable the offending PPA.

Previously, I've experienced the same issue with COPR repos lacking certain metadata info (appdata, I think). It seems like PackageKit expects all repositories to be in perfect order all the time which is unreasonable for third-party repos. If a repo is down or not up to spec, it should be skipped over.

Efforts to reproduce the problem here: https://bugs.kde.org/show_bug.cgi?id=402306

**Comment by aleixpol** [comment]
@dantti can you reproduce the issue?

**Comment by ximion** [comment]
Does this issue still exist? Please reopen this bug report in case it does!
