### ISSUE TITLE
PackageKit does not honor zypper package locks

### ISSUE THREAD

**Issue by promeneur** [PackageKit/PackageKit#325]
opensuse leap 15.1
packagekit 1.1.10

for some purpose i lock a package with the software manager according to avoid any update

then

i ask to software update plasmoid to check if there is updates

then

in the list of the packages to update there is the locked package !
it must not be in this list.

**Comment by rodrigopedra** [comment]
I came here to report the same thing. For job reasons I use MySQL and can't replace it with MariaDB. Although I have a lock set on zypper and marked MariaDB as taboo on Yast, whenever I update my system with PackageKit (through KDE Discover) it silently reinstalls MariaDB, no warnings, no nothing.

If there are any info, or logs I can provide to help, please let me know.
