### ISSUE TITLE
Offline updates broken with PackageKit 1.2.0 due to service enablement being lost in Meson conversion

### ISSUE THREAD

**Issue by AdamWill** [PackageKit/PackageKit#401]
This is an upstream report for downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1833176 . To summarize, the autotools -> Meson conversion inadvertently left out enablement of the `packagekit-offline-update.service` service in `systemd-update.target`, so now when we do the offline update boot, PackageKit just doesn't do anything at all. [This block](https://github.com/hughsie/PackageKit/blob/PACKAGEKIT_1_1_13/data/Makefile.am#L46-L49) from the old `Makefile.am` simply has no equivalent in the [new `meson.build`](https://github.com/hughsie/PackageKit/blob/master/data/meson.build).

It's not clear what the best way to fix this would be, though. Creating symlinks in meson doesn't seem to be a really [supported](https://github.com/mesonbuild/meson/issues/1602) [thing](https://github.com/mesonbuild/meson/pull/1768), and arguably we shouldn't really be doing it here; another option would be to revert [this commit from 2014](https://github.com/hughsie/PackageKit/commit/551a85fa632727e6fa3559ff7814fb159d345247) and make the service a more "normal" one again, as [systemd now cleans up the `/system-update` trigger file which was the justification for that change](https://github.com/systemd/systemd/blob/master/units/system-update-cleanup.service).

**Comment by DimStar77** [comment]
Keep https://bugzilla.redhat.com/show_bug.cgi?id=988235 in mind; the solution implemented was option b as suggested by Lennart

**Comment by hughsie** [comment]
I don't have time this week to look at the issue, but I'm happy to review patches. Sorry that's not more helpful.

**Comment by AdamWill** [comment]
I'm going to just fix it in our downstream spec for now, by creating the symlink at the end of `%install`. Other distros can do the same / the equivalent too I guess. That way we have time to figure out the best approach upstream.

**Comment by hughsie** [comment]
> I'm going to just fix it in our downstream spec for now

Much appreciated dude.

**Comment by eli-schwartz** [comment]
You should use meson.add_install_script() with something like this:

https://github.com/systemd/systemd/blob/master/tools/meson-make-symlink.sh
https://git.archlinux.org/pacman.git/tree/build-aux/meson-make-symlink.sh

**Comment by hughsie** [comment]
> You should use meson.add_install_script() with something like this:

Could you do a PR please? I always get the systemd stuff wrong. Thanks!
