### ISSUE TITLE
The HTTPS version of the website is showing a wrong resource 

### ISSUE THREAD

**Issue by zezic** [PackageKit/PackageKit#411]
Please, check the https://www.packagekit.org/
This is what I get:
![Screenshot_2020-07-08 Hughes HypnoBirthing — HypnoBirthing Classes](https://user-images.githubusercontent.com/1945127/86853588-71473500-c0bf-11ea-9ea5-aa52e8ec16b0.png)

HTTP is OK, HTTPS is broken.

**Comment by hughsie** [comment]
So I suck at nginx config I guess. This is what I'm using so far:

    server {
        if ($host = packagekit.org) {
            return 301 https://www.freedesktop.org/software/PackageKit/;
        }
        if ($host = www.packagekit.org) {
            return 301 https://www.freedesktop.org/software/PackageKit/;
        }

        listen       80;
        listen       [::]:80;
        server_name  packagekit.org www.packagekit.org;
        return 404;
    }

What I want to do is redirect *packagekit.org to https://www.freedesktop.org/software/PackageKit/ -- any ideas?

**Comment by belka-ew** [comment]
Try something like this.
```nginx
server {
    listen 80;
    listen [::]:80;
    listen 443;
    listen [::]:443;
    server_name  packagekit.org www.packagekit.org;

    return 301 https://www.freedesktop.org/software/PackageKit/;
}
```
I'm actually using `listen 443 ssl; listen [::]:443 ssl;` but since there is no any TLS-certificate, it probably doesn't matter

**Comment by hughsie** [comment]
I tried that (which fixes the http redirect), but now get this for the https:// redirect:

    The certificate is only valid for hughes-hypnobirthing.co.uk.

**Comment by JohnVeness** [comment]
As far as I can tell, packagekit.org is dead, so maybe this issue can be closed?

**Comment by zezic** [comment]
If so, then this URL should be replaced with the correct one: https://github.com/PackageKit/PackageKit/blob/adb2629113d53389b408bdf2167b1671f80ab0a6/src/org.freedesktop.PackageKit.Transaction.xml#L297C35-L297C101

**Comment by tintou** [comment]
Opened https://github.com/PackageKit/PackageKit/pull/669 for this specific occurrence
