### ISSUE TITLE
pkcon shows no version of old package after update or remove (yum / RHEL 7)

### ISSUE THREAD

**Issue by bmilar** [PackageKit/PackageKit#420]
**Description of problem:**
When updating a package by pkcon in RHEL 7, the version and source of the old package is missing in the output. Version of the new package as well as its source repo is displayed correctly.

**Version-Release number of selected component (if applicable):**
PackageKit-1.1.10-2.el7.x86_64

**How reproducible:**
Always

**Steps to Reproduce:**
1. Have a (dummy/empty) package named test-pkg-1.0-1.noarch and install it (locally).
2. Prepare a (dummy/empty) package named test-pkg-2.0-1.noarch.
3. Create a repo named pk-test-repo (using the "createrepo" utility) containing the test-pkg-2.0-1.noarch package.
4. Configure and enable the pk-test-repo on local system.
5. Run "pkcon -p -y update test-pkg".

**Actual results:**
```
Output is:
Updated      test-pkg-2.0-1.noarch (pk-test-repo)
Cleaned up   test-pkg-. ()
```

**Expected results:**
```
Output should be:
Updated      test-pkg-2.0-1.noarch (pk-test-repo)
Cleaned up   test-pkg-1.0-1.noarch (installed)
```

**Additional info:**

Similar situation happens while a package is removed, e.g.:

Actual results:
```
Output is:
Removed      test-pkg-. ()
```

Expected results:
```
Output should be:
Removed      test-pkg-1.0-1.noarch (installed)
```

Filed also downstream - rhbz1831083

**Comment by Conan-Kudo** [comment]
The YUM backend is no longer present in upstream PackageKit (it was removed in 1.2.0). From the upstream perspective, we cannot do anything. Please contact Red Hat for support on this issue for their downstream PackageKit software build with the YUM backend.
