### ISSUE TITLE
pkcon options --allow-downgrade and --allow-reinstall do not work (yum / RHEL 7)

### ISSUE THREAD

**Issue by bmilar** [PackageKit/PackageKit#421]
**Description of problem:**
When trying to use pkcon on RHEL 7 to downgrade (using --allow-downgrade) or reinstall (using --allow-reinstall) a package, the only result is a message:
`Fatal error: The packages are already all installed`

**Version-Release number of selected component (if applicable):**
PackageKit-1.1.10-2.el7.x86_64

**How reproducible:**
Always

**Steps to Reproduce (reinstall):**
1. Install a package <package_name> from an enabled repo
2. pkcon -y --allow-reinstall install <package_name>

**Steps to Reproduce (downgrade):**
1. Enable a repo with a newer version of <package_name>
2. pkcon -y install <package_name>
3. Disable the repo with a newer version of <package_name>
4. Enable a repo with an older version of <package_name>
5. pkcon -y --allow-downgrade install <package_name>

**Actual results:**
`Fatal error: The packages are already all installed`

**Expected results:**
The package should be reinstalled/downgraded.

**Additional info:**
- Works in RHEL 8 (dnf)
- Filed also downstream - rhbz1832375

**Comment by Conan-Kudo** [comment]
The YUM backend is no longer present in upstream PackageKit (it was removed in 1.2.0) and this bug affects RHEL 6, which is EOL. From the upstream perspective, we cannot do anything. Please contact Red Hat for support on this issue for their downstream PackageKit software build with the YUM backend.
