### ISSUE TITLE
Fatal error: WARNING: You are trying to remove the following essential packages: libapt-pkg5.0 (due to apt)

### ISSUE THREAD

**Issue by noorez** [PackageKit/PackageKit#434]
The issue is described in this reddit post: https://www.reddit.com/r/kdeneon/comments/i8d80x/upgrade_to_20_errors_fatal_error_warning_you_are/

Is this due to the aptcc implementation not being able to perform the 'dist-upgrade' or 'full-upgrade' feature?

**Comment by ximion** [comment]
This sounds like a bug in Neon. APTcc does the same as the apt command-line tool here (although whether full-upgrade or upgrade is performed is up to the frontend, but neither of these actions should ever result in essential packages being removed).

**Comment by ximion** [comment]
Please reopen this issue if this problem still exists.
