### ISSUE TITLE
Getting Error Type: <type 'exceptions.AttributeError'> p

### ISSUE THREAD

**Issue by danegon** [PackageKit/PackageKit#465]
Hi,

I'm getting the following error popping up several times a day on a virtual machine where I have Gnome installed:

An internal system error has occurred.
A problem that we were not expecting has occurred. Please report this bug in your distribution bugtracker with the error description

Error Type: <type 'exceptions.AttributeError'>
Error Value: 'NoneType' object has no attribute 'execute'
File : /usr/share/PackageKit/helpers/yum/yumBackend.py, line 3282, in <module>
main()
File : /usr/share/PackageKit/helpers/yum/yumBackend.py, line 3278, in main
backend = PackageKitYumBackend('', lock=True)
File : /usr/share/PackageKit/helpers/yum/yumBackend.py, line 243, in __init__
self.refresh_cache(True)
File : /usr/share/PackageKit/helpers/yum/yumBackend.py, line 1619, in refresh_cache
self.comps.refresh()
File : /usr/share/PackageKit/helpers/yum/yumComps.py, line 116, in refresh
self.cursor.execute('DELETE FROM groups
')

I also get the same error when I select System, Administration, Add/Remove Software.

I have PackageKit version 0.5.8

Could somebody please help with how I can get rid of those messages?

Thanks!

**Comment by hughsie** [comment]
RHEL7? In which case please file it in red hat bugzilla and we can process it there. That code is super old.

**Comment by danegon** [comment]
Thanks for your reply, Hughsie. Actually, I have

**Comment by Conan-Kudo** [comment]
The YUM backend is no longer present in upstream PackageKit (it was removed in 1.2.0) and this bug affects RHEL 6, which is EOL. From the upstream perspective, we cannot do anything. Please contact Red Hat for support on this issue for their downstream PackageKit software build with the YUM backend.
