### ISSUE TITLE
"Install package '%s' to provide command '%s'?" string translation not applied

### ISSUE THREAD

**Issue by AsciiWolf** [PackageKit/PackageKit#483]
The "Install package '%s' to provide command '%s'?" string is [displayed untranslated](https://user-images.githubusercontent.com/2339930/119636103-9b5b3000-be14-11eb-93cf-df4da3084883.png) on Fedora 34 Workstation (with PackageKit 1.2.3) although the string is [correctly translated](https://github.com/PackageKit/PackageKit/blob/main/po/cs.po#L625) in my (Czech) language po file and that translation is included in the 1.2.3 release.

**Comment by hughsie** [comment]
Is the LANG set correctly?

**Comment by AsciiWolf** [comment]
Yeah, it is. It works fine in all other terminal applications/commands.

**Comment by gitlab-user** [comment]
@AsciiWolf Is the output correct if you cd /usr before typing a command not installed?

**Comment by AsciiWolf** [comment]
I confirm that it works fine when I cd to /usr before typing the command. Thanks! :-)
