### ISSUE TITLE
Percentages go backwards for various operations when apt is backend

### ISSUE THREAD

**Issue by KKoukiou** [PackageKit/PackageKit#516]
In [cockpit](https://cockpit-project.org/) project we use packagekit for managing packages. We noticed that when used on ubuntu the progress bars which reflect Packagekits percentage reporting for operations go back end forward, and not having an inclining only percentage. This is 100% reproduceable from the CLI with pkcon as follows:

  ``` bash
root@ubuntu:~# pkcon resolve --plain -v cockpit-machines
10:07:28	PackageKit          Verbose debugging enabled (on console 1)
10:07:28	PackageKit          filter=(null), filters=0
10:07:28	PackageKit          adding state 0x562589849d60
10:07:28	PackageKit          role now resolve
Transaction:	Resolving
10:07:28	PackageKit          notify::connected
Status: 	Waiting in queue
Status: 	Starting
Status: 	Loading cache
Percentage:	0
Percentage:	100
Percentage:	0
Percentage:	50
Percentage:	100
Status: 	Querying
10:07:29	PackageKit          remove state 0x562589849d60
Results:
Available    cockpit-machines-215-1.all (ubuntu-focal-universe)

```

However on fedora the percentage reporting never goes backwards, for example: 

``` bash
[root@fedora-34-127-0-0-2-2201 ~]# pkcon resolve --plain -v cockpit-machines
10:07:23	PackageKit          Verbose debugging enabled (on console 1)
10:07:23	PackageKit          adding state 0x562308095560
10:07:23	PackageKit          role now resolve
Transaction:	Resolving
10:07:23	PackageKit          notify::connected
Status: 	Waiting in queue
Status: 	Starting
Percentage:	90
Percentage:	100
10:07:23	PackageKit          remove state 0x562308095560
Results:
Available    cockpit-machines-242.1-1.fc34.noarch (fedora)
Available    cockpit-machines-255-1.fc34.noarch (updates)
```

**Comment by dantti** [comment]
Well this is how apt works on cmd line too, some operations can't be known beforehand...

**Comment by dantti** [comment]
while dnf/yum had a fixed 0-50% for downloading then 0-100% for installing I prefer 0-100% for downloading then 0-100% for completion, imho it's more intuitive and it's what a deb use is used to.

**Comment by KKoukiou** [comment]
@dantti I get your point. So it seems that it's not even possible for pkgkit to fix this. In this case feel free to close the issue.

However, I still have a question. For a consumer of this API is it possible to know what sub-operations are happening in the background aside from the percentages at least? We need to show to the users something more useful that jumping percentages, so that can really expect how far are they from the command completion.

**Comment by aleixpol** [comment]
FWIW, this is something that has been also a frustration point for our users.  While I understand the thought behind the current implementation, this is something that doesn't map the experience our users expect.

**Comment by KKoukiou** [comment]
So unless this is something that is possible to improve, feel free to close the issue, as I understand that the issues really comes from apt's original behavior .

**Comment by hughsie** [comment]
Agreed, thanks.
