### ISSUE TITLE
Slackware- current: libpk_backend_slack.so: undefined symbol: BZ2_bzReadOpen

### ISSUE THREAD

**Issue by slackernetuk** [PackageKit/PackageKit#520]
Hiya,

I have no  experience whatsoever with PackageKit, the build on SlackBuilds.org is a bit outdated and created my own build.

```
    -Dsystemd=false \
    -Dpackaging_backend=slack \
    -Dgobject_introspection=true \
    -Dbash_completion=true \
    -Dpackagekit_user=root \
    -Dgstreamer_plugin=true \
    -Dgtk_module=true \
    -Dcron=true  \
    -Ddbus_sys=/usr/share/dbus-1/system.d \
    -Doffline_update=false \
    -Dman=true 
```
When I started packagekit-direct I got the error [below]

`Failed to load the backend: opening module slack failed : /usr/lib64/packagekit-backend/libpk_backend_slack.so: undefined symbol: sqlite3_bind_int `

packagekitd is slightly different:

`Failed to load the backend: opening module slack failed : /usr/lib64/packagekit-backend/libpk_backend_slack.so: undefined symbol: BZ2_bzReadOpen`

But it seems, there is conflict with sqlite?

any suggestions?

**Comment by belka-ew** [comment]
bzip2 and sqlite3 dependencies were missing in the backend. Should be fixed now in master. Thanks for reporting.

**Comment by slackernetuk** [comment]
The fix seems to work, thanks for fixing. A little question, how is the recommended way to blacklist packages?

Under below how I have changed my Slackware.conf configuration file, but the PackageKit ignores it.

```
[slackware]
Mirror=http://slackware.uk/slackware/slackware64-current/
Priority=patches;slackware64;extra;pasture;testing
Blacklist=[0-9]+_SBo;[0-9]+_snuk

```
![packagekit-blacklist](https://user-images.githubusercontent.com/54255275/145735034-4890cdb5-448b-4fa5-9259-f7fc50d742ce.png)

**Comment by belka-ew** [comment]
Sorry, I felt sick.

"Blacklist" is a single regex.
"Blacklist" is repository specific, it is evaluated during cache generation from the remote package lists, so it doesn't know about other packages in the system like _SBo. So you exclude individual packages: `Blacklist=(kernel|Cython)`.

I should probably think of a more convenient way to blacklist 3rd party packages, something like a global blacklist.
