### ISSUE TITLE
[fedora-toobox] Issues using packagekit with an integrated host and container

### ISSUE THREAD

**Issue by s2live** [PackageKit/PackageKit#540]
I am using distrobox a fedora-toolbox wrapper to configure a integrated guest and host.

Since the /user/run and /tmp folders are shared with the host any application which uses packagekit runs into issues on a guest. If packagekit is not installed on the host all pk services return nothing but errors even if pk is correctly installed on the guest and the host and guest are identical OS's. If pk is installed on the host packagekit even when called from a program on the guest, pk installs programs and files to the host and not to the guest as desired. 

Is there already an option for packagekit that enables a user to specify the path of the socket? Since this seems to be where the issue lies. Though I can guess why it wouldn't be, though it would certainly help me, I'm willing to implement this behaviour even if it won't be pulled would appreciate some pointers as to which files and functions I should be looking at altering? Also what is the default socket for packagekitd?

**Comment by hughsie** [comment]
PackageKit is just yet-another DBus daemon; I don't think it's expected to work in a container without a dbus-daemon.

**Comment by s2live** [comment]
Thanks! I should have realised, I've managed to get PackageKit running on almalinux/init-8.

Having some issues getting g-s to run on alma's dbus-deamon but hopefully will manage to resolve them!
`GLib-GIO g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed`
