### ISSUE TITLE
Portage support is not properly implemented

### ISSUE THREAD

**Issue by td5038** [PackageKit/PackageKit#546]
The support for Portage is whack. I see why the Gentoo devs don't put your code in repos. Your backend for it hasn't recieved ANY updates since January 2020. @hughsie You should investigate this yourself, and give Portage better support.

**Comment by ximion** [comment]
It's not up to him to support any backend. Backends are supported by maintainers and distributors, so it's Gentoos job to provide support. Mounir Lamouri can also possibly help, they are the last known maintainer of the portage backend.

**Comment by ximion** [comment]
It's not up to him to support any backend. Backends are supported by their own maintainers and the distributors themselves, so it's Gentoo's job to provide support. Mounir Lamouri can also possibly help, they are the last known maintainer of the portage backend.

**Comment by td5038** [comment]
Wrong. Look at the copyright.

**Comment by td5038** [comment]
Look. Harass a developer of Portage on the mailing list. The reason I filed this issue in the first place is because my GUI app store, Discover, doesn't work on Gentoo anymore.

**Comment by ximion** [comment]
Please politely raise this with Gentoo, maybe they can find someone interested in actually maintaining the portage backend and fixing issues.
