### ISSUE TITLE
Add an option to use system settings for apt/dpkg force-conf

### ISSUE THREAD

**Issue by debug-richard** [PackageKit/PackageKit#571]
I am currently working on a project that uses the PackageKit to update a Debian based embedded device.

By default, each update should overwrite the configuration files with the new version, which can be configured via /etc/apt/apt.conf.d/ and /etc/dpkg/dpkg.cfg (force-confnew). (I am aware of the problems this can cause)

The problem is that the aptcc backend enforces "force-confold" https://github.com/PackageKit/PackageKit/blob/7f0bc4b256d9c26449f2480d0e0229bbd24a2285/backends/aptcc/apt-intf.cpp#L167
and overrides the system setting in this way.

I could not find a way to disable this behavior without recompiling.

It would be great if PackageKit had a configuration option (via /etc/PackageKit/ ?) to just use the system settings for these parameters.

**Comment by ximion** [comment]
It only overrides these settings if in noninteractive mode. Maybe we can do something clever here and not override the settings if a suitable one is already set.
