### ISSUE TITLE
Packagekit seems to have DOWNgraded mod_wsgi

### ISSUE THREAD

**Issue by yengip** [PackageKit/PackageKit#581]
Hi,

I hope you can give me some pointers or work out why this has happened.  Apologies if I don't give all the information you need up front, this is all I've got for now.

At 06:55 on Friday Sep 16th 2022, packagekit running under systemd on my Debian server appears to have replaced the installed python 3.9 mod_wsgi with a python 3.7 version and broken my django web apps.  
Here's my debian version info: Linux localhost 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64.  
I don't know how to find the packagekit version info.

Here's what I see in the apache error logs.

```
[Fri Sep 16 00:00:12.595369 2022] [mpm_prefork:notice] [pid 32033] AH00163: Apache/2.4.38 (Debian) mod_wsgi/4.9.0 Python/3.9 configured -- resuming normal operations
[Fri Sep 16 00:00:12.595480 2022] [core:notice] [pid 32033] AH00094: Command line: '/usr/sbin/apache2'
[Fri Sep 16 00:00:12.872455 2022] [wsgi:info] [pid 506] mod_wsgi (pid=506): Attach interpreter ''.
...
[Fri Sep 16 06:55:43.255969 2022] [mpm_prefork:notice] [pid 32033] AH00169: caught SIGTERM, shutting down
[Fri Sep 16 06:55:43.561756 2022] [mpm_prefork:notice] [pid 3086] AH00163: Apache/2.4.38 (Debian) mod_wsgi/4.6.5 Python/3.7 configured -- resuming normal operations
```

And the syslog...

```
Sep 16 06:55:38 localhost dbus-daemon[405]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.140634' (uid=0 pid=2951 comm="/usr/bin/gdbus call --system --dest org.freedeskto")
Sep 16 06:55:38 localhost systemd[1]: Starting PackageKit Daemon...
Sep 16 06:55:38 localhost PackageKit: daemon start
Sep 16 06:55:38 localhost dbus-daemon[405]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Sep 16 06:55:38 localhost systemd[1]: Started PackageKit Daemon.
Sep 16 06:55:42 localhost libapache2-mod-wsgi-py3: apache2_invoke wsgi: already enabled
Sep 16 06:55:42 localhost systemd[1]: Reloading.
Sep 16 06:55:42 localhost systemd[1]: Stopping The Apache HTTP Server...
Sep 16 06:55:43 localhost systemd[1]: apache2.service: Succeeded.
Sep 16 06:55:43 localhost systemd[1]: Stopped The Apache HTTP Server.
Sep 16 06:55:43 localhost systemd[1]: Starting The Apache HTTP Server...

```

The server has not been rebooted for over 100 days.  The 3.9 version of mod_wsgi was installed prior to that.  packagekit was running every hour since then using a systemd timer.  I can't imagine what prompted packagekit to downgrade it at all, let alone at that specific time on that day.  I have disabled packagekit for the time being until I understand what happened.

Hope someone can give me some clues.

Many thanks,

Ian

**Comment by debug-richard** [comment]
Please check the /var/log/apt/history.log* files.
It should contain everything that happened.

**Comment by yengip** [comment]
Thanks Richard,

APT history log entry confirms what I could see in the apache log.  
```
Start-Date: 2022-09-16  06:55:41
Commandline: /usr/bin/unattended-upgrade
Upgrade: libapache2-mod-wsgi-py3:amd64 (4.6.5-1, 4.6.5-1+deb10u1)
End-Date: 2022-09-16  06:55:43
```
I don't understand why it's actually downgrading from 4.9.0 to 4.6.5.  Where is it getting it's information about what's already installed and what's the latest stable version?

Ian

**Comment by yengip** [comment]
Thanks Richard,

I appreciate your help and advice, and I apologise for posting this erroneously as a potential packagekit issue.  

Truth is, I'm not clear on the relationship between packagekit and unattended-upgrade - more googling required.

IAn
