### ISSUE TITLE
www.packagekit.org domain was domain-grabbed; policy files, docs and other components still point to it

### ISSUE THREAD

**Issue by marcusmueller** [PackageKit/PackageKit#618]
# Bug

There is multiple URLs  based in `http://www.packagekit.org` in the source code.

It seems that f-secure (as organisation) grabbed them – maybe that's even a benevolent move to avoid worse. I actually don't know why!

In any case, the domain doesn't seem to be under project control, and no links to it should be part of the source code anymore :)

# Affected files:

- policy/org.freedesktop.packagekit.policy.in
- etc/Vendor.conf
- lib/packagekit-glib2/pk-client.c
- docs/html/pk-reference.html
- docs/html/pk-faq.html
- client/pkmon.xml
- client/pkcon.xml
- PackageKit.doap

… of which, at worst the `etc/Vendor.conf` has some potential for abuse (being the URL shown to unsuspecting new users when a package can't be found). The rest is essentially project documentation.

**Comment by marcusmueller** [comment]
Note that I found this by clicking on the link at the bottom of the `pkcon` man page in fedora

**Comment by hughsie** [comment]
Yup, it's no longer being paid for by me I'm afraid. Would you be able to do a pull request to change these over to https://www.freedesktop.org/software/PackageKit/ please?

**Comment by marcusmueller** [comment]
sure, but I'll need some help with the right things to point to:

- `http://www.packagekit.org/pk-screenshots.html#gnome`:  `https://www.freedesktop.org/software/PackageKit/pk-screenshots.html` doesn't exist (from the project description XML/DOAP)
- same for `img/gpk-added-deps.png` (from the FAQ, actually)

**Comment by hughsie** [comment]
I think if the section is missing we can just rip out the URL.

> (and thank you for having paid for it before!)

Thanks, not many people say this kind of thing -- but are first to shout when somebody stops :)

**Comment by ximion** [comment]
Maybe I should have adopted the domain after all... But fortunately it isn't used for something bad now.
