### ISSUE TITLE
packagekit.org domain has been kidnapped

### ISSUE THREAD

**Issue by pedrolcl** [PackageKit/PackageKit#653]
If you point a browser to the official web site http://www.packagekit.org/ it is redirected to a suspicious domain "iyfbodn.com"

This domain is being listed as "official web site" in WikiData: https://www.wikidata.org/wiki/Q1204382

Same as #618 ?

**Comment by ximion** [comment]
This was kind of intentional, as @hughsie didn't want to continue paying for it and I didn't want to adopt it. In hindight, that was a bad idea and I should probably have adopted the domain, but it's too late now :-/
