### ISSUE TITLE
assertion failed: (transaction->priv->emitted_finished) while using Discover

### ISSUE THREAD

**Issue by berolinux** [PackageKit/PackageKit#656]
When using Discover (https://invent.kde.org/plasma/discover ) with a current PackageKit git snapshot (after commit https://github.com/PackageKit/PackageKit/commit/409ba85b00f02bfd66589b457a148cce82ad2a34 ), Discover brings up a dialog saying "Connection reset by peer".

This is caused by packagekitd failing with the assertion introduced in the commit mentioned above.

```
PackageKit:ERROR:../src/pk-transaction.c:5528:pk_transaction_dispose: assertion failed: (transaction->priv->emitted_finished)
Bail out! PackageKit:ERROR:../src/pk-transaction.c:5528:pk_transaction_dispose: assertion failed: (transaction->priv->emitted_finished)
```

FWIW removing the assert (just like using a version of PackageKit before it was introduced) makes Discover work again, but seemingly just by hiding the root problem.

**Comment by aleasto** [comment]
Indeed the new assert is hit by all transactions that bail out before reaching the backend.

In your case, and this is an educated guess, DiscoverNotifier calls GetDistroUpgrades which is unimplemented in almost all backends, triggering the assert.

I had commented about this [here](https://github.com/PackageKit/PackageKit/pull/612#issuecomment-1644597019)

I guess I'll have to fix this myself eventually, but for the moment please consider this bug a blocker for tagging a new release

**Comment by ximion** [comment]
@pwithnall Do you maybe have an idea why this is / have time to look into it?

**Comment by ximion** [comment]
I've looked into it and I am fairly confident that the patch above is the correct behavior to fix this issue. The problem was that never-committed transactions would also never emit a Finished signal, which seems to make perfect sense.

I'll also get the CI to run the daemon tests, so we can catch issues like this earlier.

**Comment by aleasto** [comment]
Yeah resolution makes sense to me as well

**Comment by pwithnall** [comment]
> I've looked into it and I am fairly confident that the patch above is the correct behavior to fix this issue. The problem was that never-committed transactions would also never emit a Finished signal, which seems to make perfect sense.

**Comment by richard-scott** [comment]
I still get this in Ubuntu 23.10 with packagekit-1.27-1, what version was this fixed in?
I normally get this crash in the Discover app after clicking the icon notifying me that updates are available.

**Comment by pwithnall** [comment]
> I still get this in Ubuntu 23.10 with packagekit-1.27-1, what version was this fixed in?

Commit 5910403 is present only in version 1.2.8 of PackageKit.
