### ISSUE TITLE
Name Problem

### ISSUE THREAD

**Issue by KitchM** [PackageKit/PackageKit#657]
I am using Debian 11 and Xfce 4.16.  Your program is listed as "Software" under System menu.  Worse, when it is opened it has no title bar.

The program is not really Software, but PackageKit and should be named as such.

Please change the naming and add a title bar to make Linux more intuitive.

Thank you.

**Comment by ximion** [comment]
This daemon is called PackageKit and has no GUI of its own. You are probably talking about GNOME Software, please raise your issues there instead.
