### ISSUE TITLE
Download transaction should not block other transactions

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#664]
From:  https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2305

Steps to reproduce:

1. Run `pkcon update -d` in console 1
2. Run `pkcon -p get-details gnome-software` in console 2

The second command is blocked by the first command, as shown below:

```
~$ pkcon -p get-details gnome-software
Transaction:	Resolving
Status: 	Waiting in queue

^C
~$
```

Due to this, all PK clients will have to wait until the download transaction is completed.

**Comment by ximion** [comment]
This is intentional, most backends do not support running these actions in parallel.
Ages ago, I implemented support for parallel transaction in PK, where backends could support running some transactions while others were also ongoing. But support from backends for this is slow, and few support it (the Yum backend and APT backend had/have support for it).
In any case, given the low adoption, I don't think frontends should rely on parallel transactions being supported and schedule tasks accordingly.

**Comment by sidt4** [comment]
Is it possible to make the support conditional ?

```py
if backend.supports_parallel_transactions ():
   do_parallel_stuff ()
else
   do_serial_stuff ()
```

**Comment by ximion** [comment]
The value of `pk_backend_supports_parallelization` is not exposed to the frontends, so they don't know how the backend will process stuff.
I also just looked at the APT backend again, the feature is still not done there and would still need a bit of work, but also an excessive amount of testing to ensure nothing breaks in a multithreaded environment.
And the code is fairly brittle...

**Comment by ximion** [comment]
Yeah, I understand that - this was the reason I implemented the parallel transaction support as a GSoC project ages ago, back then to make the Ubuntu Software Center work everywhere.
What this really needs though, after all these years, is a push to clean up backends and make them work with parallel transactions.

**Comment by sidt4** [comment]
>  If it's about to have one or the other, then I'd say the current state is better than reverting the performance fix after start.

I agree that the current fix which downloads changelog on the fly is much better than the old scenario. In the new scenario, at least we can suggest a meaningful workaround ( check changelog before clicking `Download` ), which is the most probably use case. The old scenario makes GNOME Software unusable as the `Loading Updates ...` take a long time.

**Comment by sidt4** [comment]
Is it possible to `yield();` after each package download ?

Example:

```py
for pkg in pkgs:
    download_package (pkg);
    yield();
```

**Comment by mcrha** [comment]
> at least we can suggest a meaningful workaround ( check changelog before clicking `Download` ), which is the most probably use case

I do not think so, it won't workaround/fix anything. You'd uselessly download changelogs for all updates, which is something what was requested to be avoided at the first place. Not talking there are other operations which can cause the delay, like refreshing the Updates page (either as a user action or as a reaction to plugin changes).

**Comment by sidt4** [comment]
> I do not think so, it won't workaround/fix anything. You'd uselessly download changelogs for all updates, which is something what was requested to be avoided at the first place.

Yes. That's what I meant.
