### ISSUE TITLE
Revert "trivial: Use more bitfield helpers"

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#673]
https://github.com/PackageKit/PackageKit/commit/873015877d9c1219c0d31719582551c3efc8b920 is not correct.

1. Both `GDBusMessageFlags` and `PolkitCheckAuthorizationFlags` are already bitfields ( not enums )
1. We use `pk_bitfield_contain ()` on a value which is not a PK bitfield.
1. We use `pk_bitfield_add ()` and pass it to external programs ( `polkit` ) which don't use PK bitfields.

**Comment by ximion** [comment]
Please look at what these macros do: https://github.com/PackageKit/PackageKit/blob/main/lib/packagekit-glib2/pk-bitfield.h#L50
It's literally the same code as before, just a bit more readable.
There also is no such thing as a "PK bitfield", there's just C bitfields.

**Comment by ximion** [comment]
Actually incorrect, all of these call `pk_bitfield_value` which shifts the integers *again*, even though that has already happened. So that change is indeed not right.
