### ISSUE TITLE
backends/pisi/meson.build:1:0: ERROR: File pk-backend-pisi.c does not exist.

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#680]
Something is messed up with file `"backends/pisi/pk-backend-pisi.c\n"`.

There is wierd 

- quotes
-  $
- newline 

in the filename.

```
backends/pisi $ ls
meson.build   pisiBackend.py  'pk-backend-pisi.c'$'\n'
```

**Comment by sidt4** [comment]
Also, it appears that the CI builds only dnf / apt backends. This should have been caught in CI before getting merged.

Is it possible to trigger appropriate backends depending upon the paths where changes were made.

changes in `backends/dnf` dir   -> run CI with arg `-Dpackaging_backend=dnf`
changes in `backends/alpm` dir   -> run CI with arg `-Dpackaging_backend=alpm` 

etc..

**Comment by ximion** [comment]
We can't do that as these backends require their respective package manager to be available - so we would need a CI build matrix for every distribution that has a PK backend (people are free to submit that!).

I agree that https://github.com/PackageKit/PackageKit/pull/676 should not have been merged, but this was really hard to spot...
The thing though that kind of makes me itch to immediately revert this change is the fact that this means that @erkanisik1 likely didn't try to compile this thing in the first place and test it.

That is not okay! @erkanisik1, can you please fix this and test your backend?

**Comment by sidt4** [comment]
Opened https://github.com/PackageKit/PackageKit/issues/691 to track CI build matrix.

Closing issue.
