### ISSUE TITLE
PackageKit Prevent "apt" from Upgrading the System!

### ISSUE THREAD

**Issue by sallyhaj** [PackageKit/PackageKit#739]
Hello developers,
I am using Debian Trixie with Gnome, from the last update 2.8-2, I couldn't upgrade the system, when I try so, the upgrade got stuck, like 
`Fetched 158 MB in 2s (66.4 MB/s)` 
And I can't kill the process whatever I do, with "killall packagekit" or "kill -9 [Process ID], with sudo as well, it refuses to be killed, the only solution is to reboot the system.
I asked in #debian-next channel, they suggested me to uninstall the package, but that needs to remove package like gnome and gnome-core, so it wasn't the right things to do.
The only thing I could do is to stop the packagekit service, then 'apt upgrade' the system.
Even I couldn't disable the service, and here the result:
```
sudo systemctl disable packagekit.service
The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
Also=, or Alias= settings in the [Install] section, and DefaultInstance= for
template units). This means they are not meant to be enabled or disabled using systemctl.
 
Possible reasons for having these kinds of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/, .requires/, or .upholds/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template unit
```
I only use 'apt' to update/upgrade the system, and the present of PackageKit is stopped me from doing that. What do you think about this conflict and how I can deal with it.
Thank you.

**Comment by ximion** [comment]
> And I can't kill the process whatever I do, with "killall packagekit" or "kill -9 [Process ID], with sudo as well, it refuses to be killed, the only solution is to reboot the system.

This does not look like an issue in PackageKit. The only way this could happen is if the package manager was stuck in a syscall and the kernel was busy. In any case, killing the active package manager is *terrible* advice, I am glad you didn't break your system with this!

> I am using Debian Trixie with Gnome, from the last update 2.8-2, I couldn't upgrade the system, when I try so, the upgrade got stuck, like

How are you trying to upgrade your system? Without more complete logs, there's nothing we can do.

**Comment by sallyhaj** [comment]
Hi @ximion , I am using 'sudo apt update && sudo apt upgrade' to update. and once I did that, the process refused to complete ```
and can't be killed, even I close the terminal and open a new terminal, I face this message
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-fronted. It si held by process 121234 (apt)
```
I never use gnome-software for updating/installing.
I'll try post logs in upcoming update.
Thank you.

**Comment by sidt4** [comment]
`packagekit.service` is started by GNOME Software, which itself is auto started during every login. GNOME Software runs as a background process (try `ps -aef | grep -i gnome-software`). So, `packagekit` will be always running in the first few minutes after login, and whenever GNOME Software sends commands to `packagekit`.

### Quick Fix:

1. As normal user, run:

```
$ pkill gnome-software
```

2. As root user, run:

```
# systemctl stop packagekit
```

3. Running `apt` commands should now work.

**Comment by ximion** [comment]
Actually PackageKit should shut down as soon as you start using APT - APT sends a message to PK if it's running to make it quit. If that doesn't happen, it means PK is doing something...
