### ISSUE TITLE
"pkcon get-update-detail postgresql" returns huge output (apt backend)

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#750]
This is due to the versioning used by Debian for `postgresql` package changelog. 

```
$ apt-cache policy postgresql
postgresql:
  Installed: 16+259
  Candidate: 16+260
  Version table:
     16+260 500
        500 http://httpredir.debian.org/debian sid/main amd64 Packages
        500 http://httpredir.debian.org/debian sid/main i386 Packages
 *** 16+259 100
        100 /var/lib/dpkg/status
```

```
$ apt changelog postgresql | grep urgency=
postgresql-common (260) unstable; urgency=medium
postgresql-common (259) unstable; urgency=medium
postgresql-common (258) unstable; urgency=medium
postgresql-common (257) unstable; urgency=medium
...
...
postgresql-common (20) unstable; urgency=low
postgresql-common (19) unstable; urgency=low
postgresql-common (18) unstable; urgency=low
postgresql-common (17) unstable; urgency=low
```

Here, `16+259` is considered `< 17` and hence PK returns all entries from 17 to 260 which is 200KB.

**Comment by sidt4** [comment]
GNOME Software hangs due to this issue.

Refer https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2562.

**Comment by sidt4** [comment]
I guess this is because we get changelog for `postgresql-common` when queried for `postgresql`. Both packages different version schemes.

Is this a Debian packaging bug ?

**Comment by ximion** [comment]
> Is this a Debian packaging bug ?

No, this is a valid pattern. The problem that I think we have here (without having looked at the code) is that the APT backend is using the *binary* package version to fetch the changelog, and not the *source* package version. It has to do the latter, as the versions may be different.

I'll have a look at this later as it may be trivial to fix...

**Comment by sidt4** [comment]
$ apt-get source -b postgresql
Reading package lists... Done
**Picking 'postgresql-common' as source package instead of 'postgresql'**
NOTICE: 'postgresql-common' packaging is maintained in the 'Git' version control system at:
https://salsa.debian.org/postgresql/postgresql-common.git
Please use:

**Comment by ximion** [comment]
> GNOME Software hangs due to this issue.
> 
> Refer https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2562.

To be fair, I think this is a GNOME Software bug as well, it shouldn't hang.

But also, can you try the patch linked above for me and check if that fixes the issue?

**Comment by sidt4** [comment]
> But also, can you try the patch linked above for me and check if that fixes the issue?

Yes, it fixes the issue.

**Comment by sidt4** [comment]
![gs-postgresql-fix](https://github.com/PackageKit/PackageKit/assets/128038884/965e6462-09f2-4a8b-b4e5-9cace5117d5c)

**Comment by ximion** [comment]
> Yes, it fixes the issue.

Excellent :-)
