### ISSUE TITLE
Add Garuda support

### ISSUE THREAD

**Issue by ShalokShalom** [PackageKit/PackageKit#764]
If I am reading [this log](https://dpaste.org/Jevzq) correct, then there is no `org.garudalinux.garuda` support yet implemented. 

Garuda is just Arch, so that should be easy.

**Comment by ximion** [comment]
No, this has nothing to do with PackageKit. The message is telling you that your distro is not providing an OS AppStream component: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-OS.html
