### ISSUE TITLE
Plasma discover fails due to PK enum changes

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#769]
While testing https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/2054, just wanted to double check if other PK clients pass. 

This was from Ubuntu 23.10 (all updates installed) to 24.04.

- GNOME packagekit starts the update without any issues.
- Plasma discover fails when `Update All` button is clicked in the UI as below.

### Error log:

[discover.update.error.txt](https://github.com/user-attachments/files/15744089/discover.update.error.txt)

### Screenshots (with enum change):

![plasma-discover-pk-error-1](https://github.com/PackageKit/PackageKit/assets/128038884/802f22cd-154e-4aa6-86d5-9d72769a79ac)
![plasma-discover-pk-error-2](https://github.com/PackageKit/PackageKit/assets/128038884/72dd5e4e-c662-40fc-9ae3-2de31b71814c)

### Screenshots (without enum change):

Proceeds with update.

![plasma-discover-pk-success](https://github.com/PackageKit/PackageKit/assets/128038884/9a92f1c4-a7ff-4c8e-97f7-f4804256ee21)

**Comment by sidt4** [comment]
I know this bug should be filed elsewhere in KDE. But, I've already spent a lot of time trying to reproduce this issue in KDE environment (which is totally new to me), and would rather report it somewhere before this got out of my radar.

**Comment by sidt4** [comment]
The below patch would be handy to reproduce this issue as KDE Discover tries to download changelog of 2K+ packages which takes a huge amount of time.

```diff
--- a/backends/apt/apt-job.cpp
+++ b/backends/apt/apt-job.cpp
@@ -894,13 +894,7 @@ void AptJob::stageUpdateDetail(GPtrArray *updateArray, const pkgCache::VerIterat
 
         // fetch the changelog
         pk_backend_job_set_status(m_job, PK_STATUS_ENUM_DOWNLOAD_CHANGELOG);
-        changelog = fetchChangelogData(*m_cache,
-                                       fetcher,
-                                       candver,
-                                       currver,
-                                       &update_text,
-                                       &updated,
-                                       &issued);
+        changelog = "";
     }
 
     // Check if the update was updates since it was issued
```

**Comment by ximion** [comment]
Can you report this against KDE Discover please? This change really is annoying, and tbh, in hindsight it would probably have been better to do it with a complete API/DBus interface break and split the PkInfoEnum. But we can adjust this in Discover :-)

**Comment by sidt4** [comment]
Filed https://bugs.kde.org/show_bug.cgi?id=488219

**Comment by ximion** [comment]
Nice, thanks! For the record, I have never seen this at all while running the code on my system, but I guess this is pretty much the same case as with GNOME Software.
