### ISSUE TITLE
updates failing

### ISSUE THREAD

**Issue by Grumpanon** [PackageKit/PackageKit#794]
Preparing to unpack .../update-notifier-common_3.192.54.8_all.deb ...
Unpacking update-notifier-common (3.192.54.8) ...
dpkg: error processing archive /var/cache/apt/archives/update-notifier-common_3.192.54.8_all.deb (--unpack):
 trying to overwrite '/etc/apt/apt.conf.d/10periodic', which is also in package apt-config-auto-update 2.1+nmu1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/update-notifier-common_3.192.54.8_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Grumpanon** [comment]
Operating System: KDE neon 6.0
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.2.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 125.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2

**Comment by sidt4** [comment]
This is a packaging bug, not an issue with `PackageKit`.

Refer https://bugs.launchpad.net/ubuntu/+source/apt-config-auto-update/+bug/1616689.

**Comment by Grumpanon** [comment]
Thank you, closing
