### ISSUE TITLE
Packagekit fails on jhbuild

### ISSUE THREAD

**Issue by andreasn** [PackageKit/PackageKit#85]
Tried to build gnome-software today, but jhbuild fails on Packagekit.
Not sure how much output is needed, but here is the stuff at the end
http://pastebin.com/3xuZbCZy

**Comment by hughsie** [comment]
Is that some really old NetworkManager version?

**Comment by mcatanzaro** [comment]
No, it's broken _in jhbuild_ so it's NetworkManager git master. PackageKit hasn't changed in months so it's a NetworkManager change.

Maybe http://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=159e827a72f420048e12d318f8ba1edd3f641fc8 or one of the surrounding commits is to blame. I'll ping Thomas.

**Comment by thom311** [comment]
PackageKit should include "nm-version.h", if it requires the version macros. But let's just fix it in NetworkManager as it was working before and broken by a change in NetworkManager.

NetworkManager bug here: https://bugzilla.gnome.org/show_bug.cgi?id=755660

**Comment by thom311** [comment]
For now I just reverted the offending NetworkManager commit:

master: http://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=4545a7fe9670ce4d7c259c11c2cc853bfae6729b
nm-1-0: http://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=f7234f11ad25dc9dc327fad2c300b469604dac52

**Comment by mcatanzaro** [comment]
Thanks!
